// Code generated by ent, DO NOT EDIT.

package ent

import (
	"go-template/data/db/ent/schema"
	"go-template/data/db/ent/user"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescRole is the schema descriptor for role field.
	userDescRole := userFields[5].Descriptor()
	// user.DefaultRole holds the default value on creation for the role field.
	user.DefaultRole = userDescRole.Default.(string)
	// userDescIsVip is the schema descriptor for is_vip field.
	userDescIsVip := userFields[6].Descriptor()
	// user.DefaultIsVip holds the default value on creation for the is_vip field.
	user.DefaultIsVip = userDescIsVip.Default.(bool)
	// userDescBalance is the schema descriptor for balance field.
	userDescBalance := userFields[7].Descriptor()
	// user.DefaultBalance holds the default value on creation for the balance field.
	user.DefaultBalance = userDescBalance.Default.(float64)
}
